export const skills = [
  { id: "art", name: "Arte" },
  { id: "cooking", name: "Cocina" },
  { id: "computing", name: "Computación" },
  { id: "animal-care", name: "Cuidado de animales" },
  { id: "child-care", name: "Cuidado de niños" },
  { id: "dance", name: "Danza" },
  { id: "sports", name: "Deportes" },
  { id: "teaching", name: "Enseñanza" },
  { id: "writing", name: "Escritura" },
  { id: "photography", name: "Fotografía" },
  { id: "english", name: "Inglés" },
  { id: "music", name: "Música" },
  { id: "painting", name: "Pintura" },
  { id: "theater", name: "Teatro" },
  { id: "first-aid", name: "Primeros auxilios" },
  { id: "event-planning", name: "Organización de eventos" },
  { id: "communication", name: "Comunicación" },
  { id: "teamwork", name: "Trabajo en equipo" },
  { id: "problem-solving", name: "Resolución de problemas" },
  { id: "social-support", name: "Apoyo social" },
  { id: "public-speaking", name: "Oratoria" },
  { id: "creativity", name: "Creatividad" },
  { id: "manual-work", name: "Trabajo manual" },
];
